allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// Injetar fallback do Flutter nos subprojetos/plugins de biblioteca assim que o plugin com.android.library for aplicado
subprojects {
    project.plugins.withId('com.android.library') {
        project.android.extensions.add('flutter', [
            compileSdkVersion: 34,
            minSdkVersion: 21,
            targetSdkVersion: 34,
            ndkVersion: "25.1.8937393"
        ])
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
